---

resources:
- name: dev-terraform-resource
  type: git
  source:
    uri: {{terraform-source-uri}}
    branch: {{terraform-source-branch}}

- name: pipeline-resource
  type: git
  source:
    uri: {{pipeline-source-uri}}
    branch: {{pipeline-source-branch}}


jobs:
- name: provision-dev-infrastructure
  serial: true
  plan:
  - get: dev-terraform-resource
    trigger: true
  - get: pipeline-resource
    trigger: true
  - task: plan-terraform
    file: pipeline-resource/tasks/terraform.yml
    input_mapping: {terraform-source: dev-terraform-resource, pipeline: pipeline-resource}
    params:
      TF_VAR_S3_KEY: {{s3-key}}
      AWS_DEFAULT_REGION: {{aws-default-region}}
      AWS_ACCESS_KEY_ID: {{aws-access-key-id}}
      AWS_SECRET_ACCESS_KEY: {{aws-secret-access-key}}
      TF_VAR_S3_BUCKET: {{s3-bucket}}
      TF_VAR_CF_PASSWORD: {{cf-password}}
      TF_VAR_CF_API_URL: {{cf-api-url}}
      TF_VAR_CF_PASSWORD: {{cf-password}}
      TF_VAR_CF_USER: {{cf-user}}
      TF_VAR_CF_UAA_CLIENT_ID: {{cf-uaa-client-id}}
      TF_VAR_CF_UAA_CLIENT_SECRET: {{cf-uaa-client-secret}}
      TF_VAR_CF_SKIP_SSL_VALIDATION: {{cf-skip-ssl-validation}}
