---
resources:
- name: source-code-resource
  type: git
  source:
    uri: {{source-code-resource-uri}}
    branch: {{source-code-resource-branch}}

- name: pipeline-resource
  type: git
  source:
    uri: {{pipeline-resource-uri}}
    branch: {{pipeline-resource-branch}}

jobs:
- name: job-static-analysis
  plan:
  - get: source-code-resource
    trigger: true
  - get: pipeline-resource
  - task: static-analysis
    file: pipeline-resource/tasks/sonar-analysis.yml
    input_mapping: 
      - source-code: source-code-resource
      - pipeline: pipeline-resource
    params:
      SONAR_ADDRESS: {{sonar-address}}
