---
platform: linux
image_resource:
  type: docker-image
  source: {repository: maven, tag: 3.3.9-jdk-8}

inputs:
  - name: source-code
  - name: pipeline

run:
  path: pipeline/tasks/maven-build.sh
#  path: "mvn"
#  args: ["-f", "source-code/pom.xml", "sonar:sonar", "-Dsonar.host.url=http://172.17.0.1:9000"]


