---
platform: linux
image_resource:
  type: docker-image
  source: {repository: marcialfrg/terraform, tag: 0.9.0-cf }

inputs:
  - name: terraform-source
  - name: pipeline


run:
  path: pipeline/tasks/terraform.sh
